services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pansernature
    environment:
      - REACT_APP_FIREBASE_APIKEY=${REACT_APP_FIREBASE_APIKEY}
      - REACT_APP_FIREBASE_AUTHDOMAIN=${REACT_APP_FIREBASE_AUTHDOMAIN}
      - REACT_APP_FIREBASE_PROJECTID=${REACT_APP_FIREBASE_PROJECTID}
      - REACT_APP_FIREBASE_STORAGEBUCKET=${REACT_APP_FIREBASE_STORAGEBUCKET}
      - REACT_APP_FIREBASE_MESSAGINGSENDERID=${REACT_APP_FIREBASE_MESSAGINGSENDERID}
      - REACT_APP_FIREBASE_APPID=${REACT_APP_FIREBASE_APPID}

      - REACT_APP_FB_ACCESS_TOKEN=${REACT_APP_FB_ACCESS_TOKEN}
      - REACT_APP_PAGE_ID=${REACT_APP_PAGE_ID}

      - REACT_APP_EMAILJS_USER_ID = ${REACT_APP_EMAILJS_USER_ID}
      - REACT_APP_EMAILJS_SERVICE_ID = ${REACT_APP_EMAILJS_SERVICE_ID}
      - REACT_APP_EMAILJS_TEMPLATE_ID = ${REACT_APP_EMAILJS_TEMPLATE_ID}

    volumes:
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true